import 'package:flutter/cupertino.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/absorb_pointer.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/alert_dialog.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/align.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_builder.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_container.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_cross_fade.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_default_text_style.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_list.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_modal_barrier.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_opacity.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_physical_model.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_positioned.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_size.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/animated_widget.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/app_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/aspect_ratio.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/a/asset_bundle.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/b/backdrop_filter.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/b/baseline.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/b/bottom_navigation_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/b/bottom_sheet.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/b/button_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/card.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/center.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/checkbox.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/chip.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/circle_avatar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/circular_progress_indicator.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/clip_oval.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/clip_path.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/clip_rect.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/color_filtered.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/column.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/constrained_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/container.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_action_sheet.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_activity_indicator.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_alert_dialog.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_date_picker.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_fullscreen_dialog_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_navigation_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_page_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_picker.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_popup_surface.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_scrollbar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_segmented_control.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_slider.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_switch.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_tab_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_text_field.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/cupertino_timer_picker.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/custom_multi_child_layout.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/custom_paint.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/custom_scroll_view.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/c/custom_single_child_layout.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/data_table.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/date_time_picker.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/decorated_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/decorated_box_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/default_text_style.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/dismissible.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/divider.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/drag_target.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/draggable.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/drawer.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/d/dropdown_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/e/exclude_semantics.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/e/expanded.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/e/expansion_panel.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/fade_in_image.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/fade_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/fitted_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/flat_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/floating_action_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/flow.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/flutter_logo.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/form.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/form_field.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/fractionally_sized_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/f/future_builder.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/g/gesture_detector.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/g/grid_view.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/h/hero1.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/icon.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/icon_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/ignore_pointer.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/image.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/indexed_stack.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/inherited_model.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/intrinsic_height.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/i/intrinsic_width.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/l/layout_builder.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/l/limited_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/l/linear_progress_indicator.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/l/list_body.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/l/list_tile.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/l/list_view.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/l/long_press_draggable.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/m/material_app.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/m/media_query.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/m/merge_semantics.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/n/navigator.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/n/nested_scroll_view.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/n/notification_listener.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/o/offstage.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/o/opacity.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/o/outline_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/o/overflow_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/o/overlay_entry.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/p/popup_menu_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/p/positioned_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/p/padding.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/p/paginated_data_table.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/p/placeholder.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/radio.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/raised_button.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/raw_image.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/raw_keyboard_listener.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/refresh_indicator.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/render_repaint_boundary.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/rich_text.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/rotated_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/rotation_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/r/row.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/scale_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/scroll_configuration.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/scrollbar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/semantics.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/simple_dialog.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/single_child_scroll_view.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/size_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/sized_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/sized_overflow_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/slide_transition.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/slider.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/sliver_app_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/snack_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/stack.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/stepper.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/stream_builder.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/s/swicth.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/tab_bar.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/table.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/text.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/text_field.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/theme.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/toggle_buttons.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/tooltip.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/t/transform.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/u/unconstrained_box.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/w/widgets_app.dart';
import 'package:flutter_desktop/pages/menu_page/widget_list/widgets/w/wrap.dart';

class El {
  final List<O> widgetList = [
    O("AbsorbPointer", AbsorbPointerPage()),
    O("AlertDialog", AlertDialogPage()),
    O("Align", AlignPage()),
    O("AnimatedBuilder", AnimatedBuilderPage()),
    O("AnimatedContainer", AnimatedContainerPage()),
    O("AnimatedCrossFade", AnimatedCrossFadePage()),
    O("AnimatedDefaultTextStyle", AnimatedDefaultTextStylePage()),
    O("AnimatedList", AnimatedListPage()),
    O("AnimatedModalBarrier", AnimatedModalBarrierPage()),
    O("AnimatedOpacity", AnimatedOpacityPage()),
    O("AnimatedPhysicalModel", AnimatedPhysicalModelPage()),
    O("AnimatedPositioned", AnimatedPositionedPage()),
    O("AnimatedSize", AnimatedSizePage()),
    O("AnimatedWidget", AnimatedWidgetPage()),
    O("AppBar", AppBarPage()),
    O("AspectRatio", AspectRatioPage()),
    O("AssetBundle", AssetBundlePage()),
    O("BackdropFilter", BackdropFilterPage()),
    O("Baseline", BaselinePage()),
    O("BottomNavigationBar", BottomNavigationBarPage()),
    O("BottomSheet", BottomSheetPage()),
    O("ButtonBar", ButtonBarPage()),
    O("Card", CardPage()),
    O("Center", CenterPage()),
    O("Checkbox", CheckboxPage()),
    O("Chip", ChipPage()),
    O("CircleAvatar", CircleAvatarPage()),
    O("CircularProgressIndicator", CircularProgressIndicatorPage()),
    O("ClipOval", ClipOvalPage()),
    O("ClipPath", ClipPathPage()),
    O("ClipRect", ClipRectPage()),
    O("ColorFiltered", ColorFilteredPage()),
    O("Column", ColumnPage()),
    O("ConstrainedBox", ConstrainedBoxPage()),
    O("Container", ContainerPage()),
    O("CupertinoActionSheet", CupertinoActionSheetPage()),
    O("CupertinoActivityIndicator", CupertinoActivityIndicatorPage()),
    O("CupertinoAlertDialog", CupertinoAlertDialogPage()),
    O("CupertinoButton", CupertinoButtonPage()),
    O("CupertinoDatePicker", CupertinoDatePickerPage()),
    O("CupertinoFullscreenDialogTransition", CupertinoFullscreenDialogTransitionPage()),
    O("CupertinoNavigationBar", CupertinoNavigationBarPage()),
    O("CupertinoPageTransition", CupertinoPageTransitionPage()),
    O("CupertinoPicker", CupertinoPickerPage()),
    O("CupertinoPopupSurface", CupertinoPopupSurfacePage()),
    O("CupertinoScrollbar", CupertinoScrollbarPage()),
    O("CupertinoSegmentedControl", CupertinoSegmentedControlPage()),
    O("CupertinoSlider", CupertinoSliderPage()),
    O("CupertinoSwitch", CupertinoSwitchPage()),
    O("CupertinoTabBar", CupertinoTabBarPage()),
//    O("CupertinoTabScaffold", "/CupertinoTabScaffold"),
    O("CupertinoTextField", CupertinoTextFieldPage()),
    O("CupertinoTimerPicker", CupertinoTimerPickerPage()),
    O("CustomMultiChildLayout", CustomMultiChildLayoutPage()),
    O("CustomPaint", CustomPaintPage()),
    O("CustomScrollView", CustomScrollViewPage()),
    O("CustomSingleChildLayout", CustomSingleChildLayoutPage()),
    O("DataTable", DataTablePage()),
    O("DateTimePacker", DateTimePackerPage()),
    O("DecoratedBox", DecoratedBoxPage()),
    O("DecoratedBoxTransition", DecoratedBoxTransitionPage()),
    O("DefaultTextStyle", DefaultTextStylePage()),
    O("Dismissible", DismissiblePage()),
    O("Divider", DividerPage()),
    O("DragTarget", DragTargetPage()),
    O("Draggable", DraggablePage()),
    O("Drawer", DrawerPage()),
    O("DropdownButton", DropdownButtonPage()),
    O("ExcludeSemantics", ExcludeSemanticsPage()),
    O("Expanded", ExpandedPage()),
    O("ExpansionPanel", ExpansionPanelPage()),
    O("FadeInImage", FadeInImagePage()),
    O("FadeTransition", FadeTransitionPage()),
    O("FittedBox", FittedBoxPage()),
    O("FlatButton", FlatButtonPage()),
    O("FloatingActionButton", FloatingActionButtonPage()),
    O("Flow", FlowPage()),
    O("FlutterLogo", FlutterLogoPage()),
    O("Form", FormPage()),
    O("FormField", FormFieldPage()),
    O("FractionallySizedBox", FractionallySizedBoxPage()),
    O("FutureBuilder", FutureBuilderPage()),
    O("GestureDetector", GestureDetectorPage()),
    O("GridView", GridViewPage()),
    O("Hero", HeroPage()),
    O("Icon", IconPage()),
    O("IconButton", IconButtonPage()),
    O("IgnorePointer", IgnorePointerPage()),
    O("Image", ImagePage()),
    O("IndexedStack", IndexedStackPage()),
    O("InheritedModel", InheritedModelPage()),
    O("IntrinsicHeight", IntrinsicHeightPage()),
    O("IntrinsicWidth", IntrinsicWidthPage()),
    O("LayoutBuilder", LayoutBuilderPage()),
    O("LimitedBox", LimitedBoxPage()),
    O("LinearProgressIndicator", LinearProgressIndicatorPage()),
    O("ListBody", ListBodyPage()),
    O("ListTile", ListTilePage()),
    O("ListView", ListViewPage()),
    O("LongPressDraggable", LongPressDraggablePage()),
    O("MaterialApp", MaterialAppPage()),
    O("MediaQuery", MediaQueryPage()),
    O("MergeSemantics", MergeSemanticsPage()),
    O("Navigator", NavigatorPage()),
    O("NestedScrollView", NestedScrollViewPage()),
    O("NotificationListener", NotificationListenerPage()),
    O("Offstage", OffstagePage()),
    O("Opacity", OpacityPage()),
    O("OutlineButton", OutlineButtonPage()),
    O("OverflowBox", OverflowBoxPage()),
    O("OverlayEntry", OverlayEntryPage()),
    O("Padding", PaddingPage()),
    O("Placeholder", PlaceholderPage()),
    O("PopupMenuButton", PopupMenuButtonPage()),
    O("PositionedTransition", PositionedTransitionPage()),
    O("PaginatedDataTable", PaginatedDataTablePage()),
    O("Radio", RadioPage()),
    O("RaisedButton", RaisedButtonPage()),
    O("RawImage", RawImagePage()),
    O("RawKeyboardListener", RawKeyboardListenerPage()),
    O("RefreshIndicator", RefreshIndicatorPage()),
    O("RichText", RichTextPage()),
    O("RotatedBox", RotatedBoxPage()),
    O("RotationTransition", RotationTransitionPage()),
    O("Row", RowPage()),
    O("RenderRepaintBoundary", RenderRepaintBoundaryPage()),
    O("ScaleTransition", ScaleTransitionPage()),
    O("ScrollConfiguration", ScrollConfigurationPage()),
    O("Scrollbar   !", ScrollbarPage()),
    O("Semantics   !", SemanticsPage()),
    O("SimpleDialog", SimpleDialogPage()),
    O("SingleChildScrollView", SingleChildScrollViewPage()),
    O("SizeTransition", SizeTransitionPage()),
    O("SizedBox", SizedBoxPage()),
    O("SizedOverflowBox", SizedOverflowBoxPage()),
    O("SlideTransition", SlideTransitionPage()),
    O("Slider", SliderPage()),
    O("SliverAppBar", SliverAppBarPage()),
    O("SnackBar", SnackBarPage()),
    O("Stack", StackPage()),
    O("Stepper", StepperPage()),
    O("StreamBuilder    !", StreamBuilderPage()),
    O("Switch", SwitchPage()),
    O("TabBar", WTabBarPage()),
    O("TabBarView", WTabBarPage()),
    O("Table", TablePage()),
    O("Text", TextPage()),
    O("TextField   !", TextFieldPage()),
    O("Theme", ThemePage()),
    O("ToggleButtons", ToggleButtonsPage()),
    O("Tooltip", TooltipPage()),
    O("Transform", TransformPage()),
    O("UnconstrainedBox", UnconstrainedBoxPage()),
    O("WidgetsApp", WidgetsAppPage()),
    O("Wrap", WrapPage()),
  ];
}
El el = El();

class O {
  String name;

  Widget page;

  Color color;

  O(String name, Widget page) {
    this.name = name;
    this.page = page;
  }
}
